name: Karate CI with Reports

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Compilar y ejecutar tests
        run: mvn clean test -B

      - name: Crear index.html de redirección
        if: always()
        run: |
          echo '<meta http-equiv="refresh" content="0; url=karate-summary.html">' > target/karate-reports/index.html

      - name: Deploy report to GitHub Pages
        if: always() # publica aunque haya fallos en los tests
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/karate-reports
